import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import  Demo1 from '@/components/Demo1';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <h2>Annonces récentes</h2>
        </section>
      </main>
    </>
  )
}
Home.title = "Accueil";

// Home.getLayout = function getLayout(page: any) {
//   return (
//     <div className={styles.main}>
//       <header className={styles.header}>
//         <Topbar />
//         <Navbar />
//       </header>
//       {page}
//       <Footer />
//     </div>
//   );
// };

